// data.js - Seluruh data pemanggilan wisudawan 2026
const wisudaData = {
  "F-1": {
    wali: "M. Dimaz Fitransyah, S.Pd.",
    total: 36,
    putra: 30,
    putri: 6,
    students: [
      { no: 1, induk: "1911", nama: "Aditya Bagus Setyawan", gender: "L", ortu: "Basori", univ: "", jurusan: "" },
      { no: 2, induk: "1915", nama: "Afiq Dhiaururrahman Rizqi", gender: "L", ortu: "Agus Mulyanto (Alm)", univ: "", jurusan: "" },
      { no: 3, induk: "1918", nama: "Ahmad Rizky Ardiansyah", gender: "L", ortu: "Khairul Ansory", univ: "", jurusan: "" },
      { no: 4, induk: "1948", nama: "Arya Alfatarof", gender: "L", ortu: "Supriyadi", univ: "Politeknik Energi Dan Mineral Akamigas", jurusan: "D4 Logistik Minyak Dan Gas" },
      { no: 5, induk: "1961", nama: "Baruna Tri Cahya Amaris", gender: "L", ortu: "Subandi (Alm)", univ: "", jurusan: "" },
      { no: 6, induk: "1962", nama: "Bima Sandy Ibrahim", gender: "L", ortu: "Didin Yuni Yanto", univ: "", jurusan: "" },
      { no: 7, induk: "1965", nama: "Candra Bekti Laksono Putro", gender: "L", ortu: "Sutoyo (Alm)", univ: "", jurusan: "" },
      { no: 8, induk: "1967", nama: "Chintya Alifya Ramadhani", gender: "P", ortu: "Mohamad Rofiq", univ: "Universitas Negeri Surabaya", jurusan: "S1 Matematika" },
      { no: 9, induk: "1971", nama: "Daffa Haiyun Qobus", gender: "L", ortu: "Hari Widiantoro", univ: "", jurusan: "" },
      { no: 10, induk: "1972", nama: "Danendra Nawa Pramudito", gender: "L", ortu: "Widiatmoko", univ: "", jurusan: "" },
      { no: 11, induk: "1984", nama: "Dhimaz Bayu Ramadhan", gender: "L", ortu: "Suyono", univ: "", jurusan: "" },
      { no: 12, induk: "1987", nama: "Dyah Ayu Anggraeni Puspa Dewi", gender: "P", ortu: "Nugroho Djoyo Mulyono", univ: "", jurusan: "" },
      { no: 13, induk: "1999", nama: "Fariel Hamdan Maulana", gender: "L", ortu: "Dian Widodo S.H", univ: "", jurusan: "" },
      { no: 14, induk: "2004", nama: "Galang Anugrah Santara", gender: "L", ortu: "Hadi Sumarto (Alm)", univ: "", jurusan: "" },
      { no: 15, induk: "2016", nama: "Hasbi Zulfian Idris", gender: "L", ortu: "Idris Dapat", univ: "", jurusan: "" },
      { no: 16, induk: "2035", nama: "Keisya Tarentia Artya Putri", gender: "P", ortu: "Warsono (Alm)", univ: "", jurusan: "" },
      { no: 17, induk: "2045", nama: "M Firmansyah", gender: "L", ortu: "Herlansyah", univ: "Institut Teknologi Sepuluh Nopember", jurusan: "S1 Teknik Transportasi Laut" },
      { no: 18, induk: "2048", nama: "M. Hafiz Ramadhan", gender: "L", ortu: "Misnan", univ: "", jurusan: "" },
      { no: 19, induk: "2051", nama: "M. Ramadhani Pratama", gender: "L", ortu: "Didiek Ismaya", univ: "", jurusan: "" },
      { no: 20, induk: "2071", nama: "Muhammad Dava Alfarizi", gender: "L", ortu: "Ading", univ: "", jurusan: "" },
      { no: 21, induk: "2075", nama: "Muhammad Arvarel Putra Anggara", gender: "L", ortu: "Pitono", univ: "", jurusan: "" },
      { no: 22, induk: "2077", nama: "Muhammad Faisal Avirnas", gender: "L", ortu: "Suyanto", univ: "", jurusan: "" },
      { no: 23, induk: "2092", nama: "Mukhammad Revaleyza Akbar", gender: "L", ortu: "Mukhamad Taufiq", univ: "", jurusan: "" },
      { no: 24, induk: "2108", nama: "Naufal Rizqy Pramudya", gender: "L", ortu: "Aries Tri Wahono", univ: "", jurusan: "" },
      { no: 25, induk: "2117", nama: "Pradika Satya Dinata", gender: "L", ortu: "Rudiyanto", univ: "", jurusan: "" },
      { no: 26, induk: "2127", nama: "Rafied Maulana Faqieh Putra Rahman", gender: "L", ortu: "Moh Samsir Rahman", univ: "", jurusan: "" },
      { no: 27, induk: "2133", nama: "Ramadhan Putra Hidayat", gender: "L", ortu: "Rachmat Hidayat", univ: "", jurusan: "" },
      { no: 28, induk: "2148", nama: "Robby Dwi Nurcahyo", gender: "L", ortu: "Marsalib", univ: "", jurusan: "" },
      { no: 29, induk: "2153", nama: "Safira Tiara Devi", gender: "P", ortu: "Turmudji", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Desain Komunikasi Visual" },
      { no: 30, induk: "2154", nama: "Saifullah Perwira Widyadhana Nugraha", gender: "L", ortu: "Eko Soeharno, S.E", univ: "Poltekkes Kemenkes Surabaya", jurusan: "D4 Keperawatan" },
      { no: 31, induk: "2156", nama: "Salvia Nabilah Putri Nugroho", gender: "P", ortu: "Ari Wahyu Nugroho", univ: "", jurusan: "" },
      { no: 32, induk: "2159", nama: "Satria Dwi Jasista", gender: "L", ortu: "Indah Istikarini", univ: "", jurusan: "" },
      { no: 33, induk: "2174", nama: "Vidalillah Lestari", gender: "P", ortu: "Cahyo Abadi", univ: "", jurusan: "" },
      { no: 34, induk: "2181", nama: "Yanindra Adiwidya", gender: "L", ortu: "Miyanto Yanuari", univ: "", jurusan: "" },
      { no: 35, induk: "2183", nama: "Yoga Pratama Putra Andrian", gender: "L", ortu: "Andrik Wawan Koko", univ: "", jurusan: "" },
      { no: 36, induk: "2186", nama: "Yufan Arrahman", gender: "L", ortu: "Andi Lala", univ: "", jurusan: "" }
    ]
  },
  "F-2": {
    wali: "Gita Yusanti, S.Pd.",
    total: 36,
    putra: 20,
    putri: 16,
    students: [
      { no: 1, induk: "1908", nama: "Abdul Khayyi", gender: "L", ortu: "Bukhori", univ: "", jurusan: "" },
      { no: 2, induk: "1909", nama: "Ach. Maulana Shifa", gender: "L", ortu: "Moch. Sunarto", univ: "", jurusan: "" },
      { no: 3, induk: "1912", nama: "Aditya Ramadhan Hidayat", gender: "L", ortu: "Fatah Hidayat", univ: "", jurusan: "" },
      { no: 4, induk: "1917", nama: "Agwe Cantika Ramadhani", gender: "P", ortu: "Agus Purwanto", univ: "Universitas Negeri Yogyakarta", jurusan: "D4 Pengobatan Tradisional Indonesia" },
      { no: 5, induk: "1920", nama: "Aisyah Indriyani Puspitasari", gender: "P", ortu: "Mudiyono", univ: "", jurusan: "" },
      { no: 6, induk: "1926", nama: "Alsya Alisia", gender: "P", ortu: "Anang Wijayanto", univ: "", jurusan: "" },
      { no: 7, induk: "1932", nama: "Anastasya Eka Putri Ramadani", gender: "P", ortu: "Moh. Nadir", univ: "", jurusan: "" },
      { no: 8, induk: "1957", nama: "Azizah Tri Jayanti", gender: "P", ortu: "Suhanto", univ: "Universitas Trunojoyo Madura", jurusan: "S1 Psikologi" },
      { no: 9, induk: "1963", nama: "Bintang Kautsar", gender: "L", ortu: "Arif Mawardi", univ: "", jurusan: "" },
      { no: 10, induk: "1970", nama: "Clara Salsa Isabella", gender: "P", ortu: "Sumali", univ: "Universitas Trunojoyo Madura", jurusan: "S1 Ilmu Kelautan" },
      { no: 11, induk: "1973", nama: "Danindya Raihan Aditama", gender: "L", ortu: "Simun", univ: "", jurusan: "" },
      { no: 12, induk: "1977", nama: "Davin Trianggara Wijaya", gender: "L", ortu: "Suhariyoto", univ: "", jurusan: "" },
      { no: 13, induk: "1978", nama: "Dea Nisrina Marmora", gender: "P", ortu: "Imansyah", univ: "", jurusan: "" },
      { no: 14, induk: "2006", nama: "Gavriela Fairizki Yusril Fairuz Dzaki", gender: "L", ortu: "Ir. Jusuf Seno Santoso", univ: "", jurusan: "" },
      { no: 15, induk: "2007", nama: "Gede Sutrisna Dananjaya", gender: "L", ortu: "I Made Sudiarjana", univ: "", jurusan: "" },
      { no: 16, induk: "2018", nama: "I Kadek Adi Arya Wicaksana", gender: "L", ortu: "I Wayan Putu Mandiarta", univ: "", jurusan: "" },
      { no: 17, induk: "2019", nama: "I Made Arya Anom Wicaksana Sastra", gender: "L", ortu: "I Wayan Oka Sugiartana", univ: "", jurusan: "" },
      { no: 18, induk: "2020", nama: "I Made Gede Adhika Putra Surendra", gender: "L", ortu: "Sumarno Hadi Santoso", univ: "", jurusan: "" },
      { no: 19, induk: "2037", nama: "Khamilah Saarah Haafidzah Yusroni", gender: "P", ortu: "M. Asep Yusroni", univ: "Universitas Negeri Malang", jurusan: "S1 Pendidikan Kimia" },
      { no: 20, induk: "2042", nama: "Ksatria Bayu Putra Nugraha", gender: "L", ortu: "Budi Purnomo", univ: "", jurusan: "" },
      { no: 21, induk: "2054", nama: "Malvino Mahardian Rochman", gender: "L", ortu: "Fatchur Rochman", univ: "", jurusan: "" },
      { no: 22, induk: "2057", nama: "Miken Putra Wijayakusuma", gender: "L", ortu: "Jayadi", univ: "", jurusan: "" },
      { no: 23, induk: "2065", nama: "Mohammad Fabyan Adriansyah", gender: "L", ortu: "Sugiono", univ: "", jurusan: "" },
      { no: 24, induk: "2080", nama: "Muhammad Hasballah", gender: "L", ortu: "Abdul Charies", univ: "Politeknik Perkapalan Negeri Surabaya", jurusan: "D4 Teknik Kelistrikan Kapal" },
      { no: 25, induk: "2090", nama: "Muhammad Saabiq Ghora Satria", gender: "L", ortu: "Marijan", univ: "Universitas Trunojoyo Madura", jurusan: "S1 Agroekoteknologi" },
      { no: 26, induk: "2094", nama: "Mutia Evelyn", gender: "P", ortu: "Anton Hariyono", univ: "", jurusan: "" },
      { no: 27, induk: "2096", nama: "Nabila Arissa Putri", gender: "P", ortu: "Munadi", univ: "", jurusan: "" },
      { no: 28, induk: "2192", nama: "Nafiisah Anindya Khairunnisa", gender: "P", ortu: "Rudi Hartono", univ: "", jurusan: "" },
      { no: 29, induk: "2107", nama: "Naufal Azam Falah", gender: "L", ortu: "Bambang Harianto", univ: "", jurusan: "" },
      { no: 30, induk: "2112", nama: "Ni Wayan Tiara Damayanti", gender: "P", ortu: "I Wayan Sukarena", univ: "", jurusan: "" },
      { no: 31, induk: "2128", nama: "Rahmat Wahyudi", gender: "L", ortu: "Supardi", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Hukum" },
      { no: 32, induk: "2139", nama: "Rendra Fernanda Sencoko", gender: "L", ortu: "Dony Sencoko", univ: "", jurusan: "" },
      { no: 33, induk: "2141", nama: "Revi Marischa", gender: "P", ortu: "Feri Isdian", univ: "Politeknik Negeri Jember", jurusan: "D4 Manajemen Informasi Kesehatan" },
      { no: 34, induk: "2152", nama: "Safira Dyah Pembayun", gender: "P", ortu: "Imam Safi'i", univ: "", jurusan: "" },
      { no: 35, induk: "2182", nama: "Yesi Indra Purnamasari", gender: "P", ortu: "Nur Kholis", univ: "", jurusan: "" },
      { no: 36, induk: "2184", nama: "Yolan Ghea Ifna", gender: "P", ortu: "M. Jumadi Ekotarnia S.H", univ: "Universitas Negeri Malang", jurusan: "S1 Gizi" }
    ]
  },
  "F-3": {
    wali: "Alifah Febri Khairina, S.Pd.",
    total: 36,
    putra: 21,
    putri: 15,
    students: [
      { no: 1, induk: "1927", nama: "Alvin Wahyu Ainurrohman", gender: "L", ortu: "Nuryadi", univ: "", jurusan: "" },
      { no: 2, induk: "1931", nama: "Anas Natasya Bilqis", gender: "P", ortu: "Anwar Anas", univ: "", jurusan: "" },
      { no: 3, induk: "1942", nama: "Aprilia Khaula Al-Adawiyah", gender: "P", ortu: "Rochmajudi Kustanto, S.H.", univ: "Poltekkes Kemenkes Malang", jurusan: "D3 Rekam Medis Dan Informasi Kesehatan" },
      { no: 4, induk: "1947", nama: "Artito Wahyudipta Judistira", gender: "L", ortu: "Aris Murtono", univ: "", jurusan: "" },
      { no: 5, induk: "1949", nama: "Arya Deni Lisdiansyah", gender: "L", ortu: "Dedy Setiono", univ: "", jurusan: "" },
      { no: 6, induk: "1953", nama: "Aura Brilian Noviyanti", gender: "P", ortu: "Ali Sodiqin", univ: "UPN Veteran Yogyakarta", jurusan: "S1 Teknik Geomatika" },
      { no: 7, induk: "1958", nama: "Azka Ainazar Zamzami", gender: "L", ortu: "Nasrulloh Baihaqi", univ: "", jurusan: "" },
      { no: 8, induk: "1964", nama: "Briva Rizky Maulana Irwanto", gender: "L", ortu: "Bambang Irwanto", univ: "", jurusan: "" },
      { no: 9, induk: "1975", nama: "Dava Ariatna Alfarezhi", gender: "L", ortu: "Muhamad Aminin M", univ: "", jurusan: "" },
      { no: 10, induk: "1990", nama: "Elsa Dwi Chintia Putri", gender: "P", ortu: "Budi Teguh Santoso", univ: "", jurusan: "" },
      { no: 11, induk: "1991", nama: "Elza Revania Putri", gender: "P", ortu: "Zaenal Abidin", univ: "Institut Teknologi Sepuluh Nopember", jurusan: "S1 Teknologi Kedokteran" },
      { no: 12, induk: "1993", nama: "Fabio Nuki Eka Saputra", gender: "L", ortu: "Suhartono", univ: "", jurusan: "" },
      { no: 13, induk: "1998", nama: "Farhesa Adila Nugroho", gender: "L", ortu: "Catur Kurnia Adi", univ: "", jurusan: "" },
      { no: 14, induk: "2011", nama: "Hafidz Rizky Romadoni", gender: "L", ortu: "Iid Nastajib", univ: "", jurusan: "" },
      { no: 15, induk: "2013", nama: "Hanif Rasik Hakim", gender: "L", ortu: "Yamto Mulyono", univ: "Universitas Airlangga", jurusan: "S1 Keperawatan" },
      { no: 16, induk: "2029", nama: "Joice Bella Indriantika", gender: "P", ortu: "Johan Susilo", univ: "", jurusan: "" },
      { no: 17, induk: "2034", nama: "Kayla Bilqis Arthalia", gender: "P", ortu: "Suwana Budi", univ: "", jurusan: "" },
      { no: 18, induk: "2049", nama: "M. Haikal Alamhudi Dzulhaqqi", gender: "L", ortu: "Dedi Setiawan", univ: "", jurusan: "" },
      { no: 19, induk: "2063", nama: "Mochammad Rifan Afifi", gender: "L", ortu: "Zainul Afif", univ: "", jurusan: "" },
      { no: 20, induk: "2068", nama: "Muhamad Irfad Fandi Abdillah", gender: "L", ortu: "Imam Wahyudi", univ: "", jurusan: "" },
      { no: 21, induk: "2069", nama: "Muhammad Alfa Rizzi Aldiansyah", gender: "L", ortu: "Rony Christiawan", univ: "", jurusan: "" },
      { no: 22, induk: "2079", nama: "Muhammad Fath Rasya Setyawan", gender: "L", ortu: "Rukminto Yudi Setyawan, S.T.", univ: "", jurusan: "" },
      { no: 23, induk: "2082", nama: "Muhammad Ilham Gufianto", gender: "L", ortu: "Gufron", univ: "", jurusan: "" },
      { no: 24, induk: "2086", nama: "Muhammad Nybras Durroyya Attaqi", gender: "L", ortu: "Muttaqin", univ: "", jurusan: "" },
      { no: 25, induk: "2087", nama: "Muhammad Rafkha Zaidan", gender: "L", ortu: "Helmi Hermanto, S.Sos", univ: "", jurusan: "" },
      { no: 26, induk: "2101", nama: "Nadiyah Puspa Sari", gender: "P", ortu: "Djoko Subiyanto", univ: "Poltekkes Kemenkes Surabaya", jurusan: "D3 Keperawatan" },
      { no: 27, induk: "2102", nama: "Najwa Deswinta Syaharani", gender: "P", ortu: "Suwignyo", univ: "Poltekkes Kemenkes Malang", jurusan: "D4 Keselamatan & Kesehatan Kerja" },
      { no: 28, induk: "2103", nama: "Narendra Raditya Afrizal", gender: "L", ortu: "Sapriadi", univ: "", jurusan: "" },
      { no: 29, induk: "2109", nama: "Naya Alodia Sari Adinata", gender: "P", ortu: "Noto Rejo", univ: "", jurusan: "" },
      { no: 30, induk: "2114", nama: "Novianti Puspita Ningrum", gender: "P", ortu: "Suwarno", univ: "", jurusan: "" },
      { no: 31, induk: "2124", nama: "Rado Dwi Anugrah Nasta'in Putra", gender: "L", ortu: "M.H. Nasta'in", univ: "", jurusan: "" },
      { no: 32, induk: "2136", nama: "Rania Faiqotul Himma Arif Putri", gender: "P", ortu: "Arif Supriyono", univ: "Universitas Negeri Malang", jurusan: "S1 Kimia" },
      { no: 33, induk: "2146", nama: "Rifkhi Ahmadhika", gender: "L", ortu: "Witanto", univ: "", jurusan: "" },
      { no: 34, induk: "2164", nama: "Shinta Bunga Anggraini", gender: "P", ortu: "Hari Purwanto", univ: "", jurusan: "" },
      { no: 35, induk: "2175", nama: "Vindy Dwi Agita Putri", gender: "P", ortu: "Agus Rumawan", univ: "Universitas Brawijaya", jurusan: "S1 Kebidanan" },
      { no: 36, induk: "2176", nama: "Vinza Aleisya Cahya Khoirunnisa", gender: "P", ortu: "Moch Soleh", univ: "", jurusan: "" }
    ]
  },
  "F-4": {
    wali: "Moch. Salim Imron, S.Pd.",
    total: 33,
    putra: 22,
    putri: 11,
    students: [
      { no: 1, induk: "1916", nama: "Afrizal Risky Dirgantara", gender: "L", ortu: "Slamet", univ: "", jurusan: "" },
      { no: 2, induk: "1921", nama: "Aisyah Nur Safitri", gender: "P", ortu: "Muh. Lazim", univ: "", jurusan: "" },
      { no: 3, induk: "1922", nama: "Al-Fatih Izzamudin Azka", gender: "L", ortu: "Ferry Eka Aprillia, S.Pd.", univ: "", jurusan: "" },
      { no: 4, induk: "1923", nama: "Alcito Armana Geraldy", gender: "L", ortu: "Darmono Hadi", univ: "", jurusan: "" },
      { no: 5, induk: "1924", nama: "Aldrich Gerrard Starly Paleba", gender: "L", ortu: "Donald Jechson Paleba", univ: "", jurusan: "" },
      { no: 6, induk: "1937", nama: "Angga Putra Firmansyah", gender: "L", ortu: "Agus Basuki", univ: "", jurusan: "" },
      { no: 7, induk: "1959", nama: "Azmil Dhea Lailatul Izza", gender: "P", ortu: "Syaiful Mubin", univ: "", jurusan: "" },
      { no: 8, induk: "1992", nama: "Evan Raissa Oktavianda", gender: "L", ortu: "Endra Santosa", univ: "", jurusan: "" },
      { no: 9, induk: "1994", nama: "Fahrani Widya Sari", gender: "P", ortu: "Risal Fauji", univ: "", jurusan: "" },
      { no: 10, induk: "1996", nama: "Faizah Putri Aurel", gender: "P", ortu: "Juni Hariyanto", univ: "", jurusan: "" },
      { no: 11, induk: "2005", nama: "Galang Satria Sofian", gender: "L", ortu: "Alfan Soefian", univ: "", jurusan: "" },
      { no: 12, induk: "2009", nama: "Giovanni Widyatmoko", gender: "L", ortu: "Musfiddin, S.T.", univ: "", jurusan: "" },
      { no: 13, induk: "2017", nama: "Husain Ali", gender: "L", ortu: "Yahya Chalid", univ: "", jurusan: "" },
      { no: 14, induk: "2022", nama: "Immanuel Rasya Jaya Pratama", gender: "L", ortu: "Rahmad Agung Wijaya", univ: "", jurusan: "" },
      { no: 15, induk: "2055", nama: "Margareth Liliana Lukman Simbolon", gender: "P", ortu: "Robin Lukman Simbolon", univ: "", jurusan: "" },
      { no: 16, induk: "2056", nama: "Meyshia Putri Wandaya", gender: "P", ortu: "Swandaya", univ: "", jurusan: "" },
      { no: 17, induk: "2072", nama: "Muhammad Asy Syams", gender: "L", ortu: "Sudarno", univ: "", jurusan: "" },
      { no: 18, induk: "2083", nama: "Muhammad Naufal Hafizh Iram", gender: "L", ortu: "Bambang Tri Sambodo", univ: "", jurusan: "" },
      { no: 19, induk: "2084", nama: "Muhammad Nur Iman Bayu Aji Restu Istika", gender: "L", ortu: "Nur Basuki S.Sos", univ: "", jurusan: "" },
      { no: 20, induk: "2089", nama: "Muhammad Rizq Hisaam", gender: "L", ortu: "Heny Andrysol", univ: "", jurusan: "" },
      { no: 21, induk: "2093", nama: "Murobby Patih Al Farroz", gender: "L", ortu: "Didik Puriyanto", univ: "", jurusan: "" },
      { no: 22, induk: "2098", nama: "Nadia Aqila Jala Ningtyas", gender: "P", ortu: "Dirgantoro", univ: "Politeknik Negeri Malang", jurusan: "D4 Teknologi Kimia Industri" },
      { no: 23, induk: "2134", nama: "Randy Aditya Rahman", gender: "L", ortu: "Abdul Rahman", univ: "", jurusan: "" },
      { no: 24, induk: "2135", nama: "Rangga Arya Pratama", gender: "L", ortu: "Agung Irawan", univ: "", jurusan: "" },
      { no: 25, induk: "2138", nama: "Reivan Giorgie", gender: "L", ortu: "Dyah Susilowati", univ: "", jurusan: "" },
      { no: 26, induk: "2143", nama: "Rezvan Miftahul Sugiarto", gender: "L", ortu: "Bambang Sugiarto", univ: "", jurusan: "" },
      { no: 27, induk: "2144", nama: "Rheihan Iqbal Baskara", gender: "L", ortu: "Kisriyono", univ: "", jurusan: "" },
      { no: 28, induk: "2147", nama: "Rizqi Cigra Akbar", gender: "L", ortu: "Koesnanto", univ: "", jurusan: "" },
      { no: 29, induk: "2160", nama: "Sekar Ageng Kristia Ningrum", gender: "P", ortu: "Suradji", univ: "", jurusan: "" },
      { no: 30, induk: "2191", nama: "Tiara Amelia Azzahra", gender: "P", ortu: "Suyitno", univ: "Universitas Airlangga", jurusan: "D3 Perpajakan" },
      { no: 31, induk: "2173", nama: "Verlita Aura Oktaviani", gender: "P", ortu: "Fajar Shodiq", univ: "UIN Sunan Ampel Surabaya", jurusan: "S1 Akuntansi" },
      { no: 32, induk: "2177", nama: "Vivian Marthen Liem", gender: "P", ortu: "Marthen", univ: "", jurusan: "" },
      { no: 33, induk: "2179", nama: "Wildan Muh Aziz Al Muttaqin", gender: "L", ortu: "Dalinu", univ: "Poltekkes Kemenkes Surabaya", jurusan: "D3 Teknologi Laboratorium Medis" }
    ]
  },
  "F-5": {
    wali: "Septi Rosiana Dewi, S.Si.",
    total: 35,
    putra: 14,
    putri: 21,
    students: [
      { no: 1, induk: "1910", nama: "Adelia Chika Putri Febriyanti", gender: "P", ortu: "Mochammad Bastoni", univ: "", jurusan: "" },
      { no: 2, induk: "1913", nama: "Adonis William Krisma Waruwu", gender: "L", ortu: "Desima Waruwu", univ: "", jurusan: "" },
      { no: 3, induk: "1933", nama: "Andi Yosia Imanuel", gender: "L", ortu: "Andi Subroto", univ: "", jurusan: "" },
      { no: 4, induk: "1936", nama: "Andri Kurniawan", gender: "L", ortu: "Abdu Salam", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Teknik Industri" },
      { no: 5, induk: "1945", nama: "Ariya Vinodhion Regitama", gender: "L", ortu: "Nur Kasan", univ: "", jurusan: "" },
      { no: 6, induk: "1955", nama: "Ayu Mulia Bened Marhanis", gender: "P", ortu: "Benediktus Paryanto", univ: "", jurusan: "" },
      { no: 7, induk: "1960", nama: "Balqis Alizza Rismala", gender: "P", ortu: "Ali Fatchur Rohman", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Kedokteran" },
      { no: 8, induk: "1966", nama: "Chintia Fitri Rahayu", gender: "P", ortu: "Sugiyanto", univ: "", jurusan: "" },
      { no: 9, induk: "1968", nama: "Chriscentia Harum Nugroho", gender: "P", ortu: "Dhani Bagus Nugroho", univ: "", jurusan: "" },
      { no: 10, induk: "1981", nama: "Devinta Jala Mandalika", gender: "P", ortu: "Supriono", univ: "", jurusan: "" },
      { no: 11, induk: "1983", nama: "Dhimas Satrio Utomo", gender: "L", ortu: "Gatot Jati Kiswanto", univ: "", jurusan: "" },
      { no: 12, induk: "1986", nama: "Dwi Indah Safitri", gender: "P", ortu: "Isnul Huda (Alm)", univ: "", jurusan: "" },
      { no: 13, induk: "1997", nama: "Farel Gading Hartono", gender: "L", ortu: "Hartono Eko Wadi", univ: "", jurusan: "" },
      { no: 14, induk: "2003", nama: "Fitri Yatul Habibah", gender: "P", ortu: "Purnomo", univ: "Institut Teknologi Sepuluh Nopember", jurusan: "S1 Matematika" },
      { no: 15, induk: "2010", nama: "Gladys Setya Putri Artika", gender: "P", ortu: "Muchli Zartika", univ: "UIN Maulana Malik Ibrahim Malang", jurusan: "S1 Farmasi" },
      { no: 16, induk: "2028", nama: "Jihan Salwa Dwi Rahayu", gender: "P", ortu: "Rakidi (Alm)", univ: "", jurusan: "" },
      { no: 17, induk: "2030", nama: "Juan Fairuz Akbar Bhama Kerti", gender: "L", ortu: "Poedji Tjahyono (Alm)", univ: "", jurusan: "" },
      { no: 18, induk: "2044", nama: "Lucas Farrel Noah", gender: "L", ortu: "Atok Subiyanto", univ: "", jurusan: "" },
      { no: 19, induk: "2058", nama: "Mikhael Jerry", gender: "L", ortu: "Lucky Soepriatman", univ: "", jurusan: "" },
      { no: 20, induk: "2070", nama: "Muhammad Alvan Putra Safi'i", gender: "L", ortu: "Imam Safi'i", univ: "", jurusan: "" },
      { no: 21, induk: "2106", nama: "Nathania Aurellie Singgiharto", gender: "P", ortu: "Agus Singgiharto", univ: "", jurusan: "" },
      { no: 22, induk: "2110", nama: "Nayla Nazwa Syafira", gender: "P", ortu: "Moh. Purwanto", univ: "", jurusan: "" },
      { no: 23, induk: "2111", nama: "Nayya Destiani", gender: "P", ortu: "Budi Waluyo", univ: "", jurusan: "" },
      { no: 24, induk: "2116", nama: "Oktamelia Rahma Tohari", gender: "P", ortu: "Chamim Tohari", univ: "", jurusan: "" },
      { no: 25, induk: "2119", nama: "Putri Fauziyah Andini", gender: "P", ortu: "Moh. Sobir", univ: "", jurusan: "" },
      { no: 26, induk: "2126", nama: "Raffel Aditya Syahputra", gender: "L", ortu: "Nursin", univ: "", jurusan: "" },
      { no: 27, induk: "2130", nama: "Raisah Rizqi Naira", gender: "P", ortu: "Herniawan", univ: "", jurusan: "" },
      { no: 28, induk: "2140", nama: "Restu Bumi", gender: "P", ortu: "Agung", univ: "", jurusan: "" },
      { no: 29, induk: "2145", nama: "Ridwan Athallah Zachrie", gender: "L", ortu: "Wahyu Irawan", univ: "Poltekkes Kemenkes Surabaya", jurusan: "D4 Keperawatan" },
      { no: 30, induk: "2149", nama: "Romy Alireza", gender: "L", ortu: "Siswoyo", univ: "", jurusan: "" },
      { no: 31, induk: "2150", nama: "Sacha Laura Dominique", gender: "P", ortu: "Tri Supartono", univ: "", jurusan: "" },
      { no: 32, induk: "2158", nama: "Santa Christian Vernando", gender: "L", ortu: "Budi Santoso", univ: "", jurusan: "" },
      { no: 33, induk: "2163", nama: "Shereen Zaizafun Daiman Putri", gender: "P", ortu: "Daiman", univ: "", jurusan: "" },
      { no: 34, induk: "2170", nama: "Tita Nanda Dwi Karunia", gender: "P", ortu: "Budi Utomo", univ: "", jurusan: "" },
      { no: 35, induk: "2171", nama: "Tri Wulan Sabila Ramadhani", gender: "P", ortu: "Paini", univ: "", jurusan: "" }
    ]
  },
  "F-6": {
    wali: "Pungki Triyanto, M.Pd.",
    total: 36,
    putra: 20,
    putri: 16,
    students: [
      { no: 1, induk: "1914", nama: "Afifah Tsuraya Haziqah", gender: "P", ortu: "Hermawan Wicaksana Putra", univ: "UIN Sunan Ampel Surabaya", jurusan: "S1 Sosiologi" },
      { no: 2, induk: "1919", nama: "Ainiya Hana", gender: "P", ortu: "Mokhamad Ridwan", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Administrasi Publik" },
      { no: 3, induk: "1930", nama: "Amalia Istiqomah", gender: "P", ortu: "Suyono", univ: "", jurusan: "" },
      { no: 4, induk: "1934", nama: "Andra Akhbar Satria Putra", gender: "L", ortu: "Samsul Hidayat", univ: "", jurusan: "" },
      { no: 5, induk: "1940", nama: "Annisa Azzahra Maulani Putri", gender: "P", ortu: "Khoirul Anam", univ: "", jurusan: "" },
      { no: 6, induk: "1943", nama: "Apriliana Azizah Putri", gender: "P", ortu: "Edi Purwanto", univ: "", jurusan: "" },
      { no: 7, induk: "1944", nama: "Araka Hasya", gender: "L", ortu: "Bayu Yusti Yuwana", univ: "", jurusan: "" },
      { no: 8, induk: "1951", nama: "Arya Tri Husada", gender: "L", ortu: "Anang Suwandi", univ: "", jurusan: "" },
      { no: 9, induk: "1956", nama: "Aziiz Abdul Razzaaq", gender: "L", ortu: "Darman", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Hubungan Internasional" },
      { no: 10, induk: "2189", nama: "Bintang Maulana Hafiiz", gender: "L", ortu: "Iswahyudi", univ: "", jurusan: "" },
      { no: 11, induk: "1979", nama: "Decko Saseno Wijaya", gender: "L", ortu: "Decky Wijaya", univ: "", jurusan: "" },
      { no: 12, induk: "1988", nama: "Dzu Izzi Ahmad Iklila", gender: "L", ortu: "Muladi (Alm)", univ: "", jurusan: "" },
      { no: 13, induk: "1995", nama: "Fahriansyah Yuliandaro Siregar", gender: "L", ortu: "Yunus Syarifuddin Siregar", univ: "", jurusan: "" },
      { no: 14, induk: "2000", nama: "Febriana Az-Zahra Waani", gender: "P", ortu: "Muhaimin", univ: "Politeknik Perkapalan Negeri Surabaya", jurusan: "D4 Manajemen Bisnis" },
      { no: 15, induk: "2001", nama: "Feliecia Az-Zahra", gender: "P", ortu: "Moch Supi'i", univ: "", jurusan: "" },
      { no: 16, induk: "2023", nama: "Indi Adina Kurnia", gender: "P", ortu: "Zaki Kurnia", univ: "", jurusan: "" },
      { no: 17, induk: "2025", nama: "Jennya Ladysta Sri Priyanti", gender: "P", ortu: "Supriyanto", univ: "UIN Sunan Ampel Surabaya", jurusan: "S1 Psikologi" },
      { no: 18, induk: "2031", nama: "Juandika Maulana", gender: "L", ortu: "Indarto", univ: "", jurusan: "" },
      { no: 19, induk: "2036", nama: "Keyzha Martha Zerlina Putri", gender: "P", ortu: "Doris Prasetyono", univ: "", jurusan: "" },
      { no: 20, induk: "2050", nama: "M. Rama Hartawan", gender: "L", ortu: "Amirul Mu'minin", univ: "", jurusan: "" },
      { no: 21, induk: "2053", nama: "Mukhamad Yusuf Arya Suta", gender: "L", ortu: "Dwi Siswanto", univ: "", jurusan: "" },
      { no: 22, induk: "2061", nama: "Moch. Rizal", gender: "L", ortu: "Bambang Triyono", univ: "", jurusan: "" },
      { no: 23, induk: "2062", nama: "Mochammad Isro' Irsyad N.", gender: "L", ortu: "Soirodin", univ: "", jurusan: "" },
      { no: 24, induk: "2067", nama: "Muhamad Giland Ramadhan", gender: "L", ortu: "Suyatno", univ: "", jurusan: "" },
      { no: 25, induk: "2076", nama: "Muhammad Fahri Javier Asyifa'", gender: "L", ortu: "Suwandik", univ: "", jurusan: "" },
      { no: 26, induk: "2078", nama: "Muhammad Farel Dyca Irawan", gender: "L", ortu: "Rumandi (Alm)", univ: "", jurusan: "" },
      { no: 27, induk: "2091", nama: "Muhammad Yusuf Abyztha Endrisma", gender: "L", ortu: "Endra Setyo Budi", univ: "", jurusan: "" },
      { no: 28, induk: "2104", nama: "Natasya Salsabillah", gender: "P", ortu: "Moch Wahib", univ: "", jurusan: "" },
      { no: 29, induk: "2120", nama: "Putri Nur Ainiyah Salsabilah", gender: "P", ortu: "Nur Qomari", univ: "", jurusan: "" },
      { no: 30, induk: "2131", nama: "Raisya Nazwa Pradisti", gender: "P", ortu: "Pambudi Juniarto", univ: "", jurusan: "" },
      { no: 31, induk: "2137", nama: "Rechan Alfarel Ramadhani", gender: "L", ortu: "Agus Toni Sapto Budhiarto", univ: "", jurusan: "" },
      { no: 32, induk: "2151", nama: "Safinatun Najah", gender: "P", ortu: "Irawan", univ: "Universitas Brawijaya", jurusan: "S1 Perencanaan Wilayah & Kota" },
      { no: 33, induk: "2157", nama: "Sandy Dimas Kurniawan Prayoga", gender: "L", ortu: "Supriyantono", univ: "", jurusan: "" },
      { no: 34, induk: "2167", nama: "Tasya Agustia", gender: "P", ortu: "Solichan Noor", univ: "", jurusan: "" },
      { no: 35, induk: "2178", nama: "Wahyu Aprilia Guritno", gender: "P", ortu: "Kariono", univ: "", jurusan: "" },
      { no: 36, induk: "2188", nama: "Zico Canavaro Putra Ananto", gender: "L", ortu: "Tri Yunianto", univ: "", jurusan: "" }
    ]
  },
  "F-7": {
    wali: "Sintya Risyulianita Masella, S.Pd.",
    total: 32,
    putra: 20,
    putri: 12,
    students: [
      { no: 1, induk: "1939", nama: "Anggra Teguh Samudera", gender: "L", ortu: "Teguh Raharjo", univ: "", jurusan: "" },
      { no: 2, induk: "1941", nama: "Anugrah Yuan Putra", gender: "L", ortu: "Andri Kurniawan", univ: "", jurusan: "" },
      { no: 3, induk: "1950", nama: "Arya Dimas Putra", gender: "L", ortu: "Zaldy", univ: "", jurusan: "" },
      { no: 4, induk: "1969", nama: "Christyo Bimo Saputro", gender: "L", ortu: "Satyo Ari Wibowo", univ: "", jurusan: "" },
      { no: 5, induk: "1974", nama: "Danu Reza", gender: "L", ortu: "Bahari Stiok", univ: "", jurusan: "" },
      { no: 6, induk: "1985", nama: "Dimas Alif Putra Alfahrizi", gender: "L", ortu: "Mokhammad Rofik", univ: "", jurusan: "" },
      { no: 7, induk: "2012", nama: "Hafizh Al Mughny", gender: "L", ortu: "Mauidatul Hasanah", univ: "", jurusan: "" },
      { no: 8, induk: "2014", nama: "Hanifa Putri Aulia", gender: "P", ortu: "Sutris", univ: "", jurusan: "" },
      { no: 9, induk: "2021", nama: "Ignatius Giovani Tri Juniarto", gender: "L", ortu: "Yohanes B. Anang Suhardianto", univ: "", jurusan: "" },
      { no: 10, induk: "2024", nama: "Jelita Syifarani", gender: "P", ortu: "Martoyo", univ: "", jurusan: "" },
      { no: 11, induk: "2027", nama: "Jessica Putri Devina", gender: "P", ortu: "Budiriva", univ: "", jurusan: "" },
      { no: 12, induk: "2032", nama: "Jufrian Dimas Saputra", gender: "L", ortu: "Achmad Djufri", univ: "", jurusan: "" },
      { no: 13, induk: "2033", nama: "Kaneisya Anadyaza", gender: "P", ortu: "Aan Kurniawan", univ: "", jurusan: "" },
      { no: 14, induk: "2039", nama: "Kinanti Dwi Arthalita", gender: "P", ortu: "Abdulloh", univ: "", jurusan: "" },
      { no: 15, induk: "2041", nama: "Kirana Nadiyah Restu Permono", gender: "P", ortu: "Adi Permono", univ: "", jurusan: "" },
      { no: 16, induk: "2043", nama: "Louisa Kathleen Anastasia Armansyah", gender: "P", ortu: "Wody Armansyah S.E", univ: "", jurusan: "" },
      { no: 17, induk: "2052", nama: "Muhammad Sulthan Nafis Muhtaram", gender: "L", ortu: "Dwi Purnomo", univ: "", jurusan: "" },
      { no: 18, induk: "2059", nama: "Moch. Akbar Putra Yalasena", gender: "L", ortu: "Rudy Sumariyono S.H.", univ: "", jurusan: "" },
      { no: 19, induk: "2066", nama: "Mohammad Farhad Fauqi", gender: "L", ortu: "Mochamad Achmadi", univ: "", jurusan: "" },
      { no: 20, induk: "2073", nama: "Muhammad Beryl Atha Majaya", gender: "L", ortu: "Yusroni", univ: "", jurusan: "" },
      { no: 21, induk: "2074", nama: "Muhammad Daffa Aswangga", gender: "L", ortu: "Aris Budiono", univ: "", jurusan: "" },
      { no: 22, induk: "2081", nama: "Muhammad Ibrahim Syahputra", gender: "L", ortu: "Nur Hasyim", univ: "", jurusan: "" },
      { no: 23, induk: "2095", nama: "Nabil Akhtar Firdaus", gender: "L", ortu: "Iwan Kusmiadi", univ: "", jurusan: "" },
      { no: 24, induk: "2100", nama: "Nadia Vega", gender: "P", ortu: "Erik Wahyudi", univ: "", jurusan: "" },
      { no: 25, induk: "2122", nama: "Radhitya Rasyidhin", gender: "L", ortu: "Rully Raharjo", univ: "", jurusan: "" },
      { no: 26, induk: "2125", nama: "Rafael Rio Fritz Armawan", gender: "L", ortu: "Andri Armawan", univ: "", jurusan: "" },
      { no: 27, induk: "2129", nama: "Raihan Fachri Ar - Rasyid", gender: "L", ortu: "Rosyid", univ: "", jurusan: "" },
      { no: 28, induk: "2142", nama: "Reysha Hartika Aprilyanti", gender: "P", ortu: "Hariyono Hendra Setyawan", univ: "", jurusan: "" },
      { no: 29, induk: "2155", nama: "Salsabila Nur Zam", gender: "P", ortu: "Zamroni (Alm)", univ: "", jurusan: "" },
      { no: 30, induk: "2165", nama: "Sindy Aulia Nur Agustin Santoso", gender: "P", ortu: "Puguh Santoso", univ: "", jurusan: "" },
      { no: 31, induk: "2169", nama: "Tiara Jane Amalia Putri", gender: "P", ortu: "Sajidin (Alm)", univ: "", jurusan: "" },
      { no: 32, induk: "2185", nama: "Yuda", gender: "L", ortu: "Purnomo", univ: "", jurusan: "" }
    ]
  },
  "F-8": {
    wali: "Putri Amalia Salsabila, S.Pd.",
    total: 32,
    putra: 15,
    putri: 21,
    students: [
      { no: 1, induk: "1925", nama: "Alriska Vonickiranadyah Paramadewi", gender: "P", ortu: "Yudi Darmawan", univ: "", jurusan: "" },
      { no: 2, induk: "1928", nama: "Alyaa' Yumnaa", gender: "P", ortu: "Sutejo", univ: "Universitas Negeri Surabaya", jurusan: "S1 Sosiologi" },
      { no: 3, induk: "1929", nama: "Alycia Tara Dewi Hardiyanti", gender: "P", ortu: "Kokok Hardioko", univ: "", jurusan: "" },
      { no: 4, induk: "1938", nama: "Anggie Ilmi Nafiq Ariesta", gender: "P", ortu: "Suyagi", univ: "", jurusan: "" },
      { no: 5, induk: "1946", nama: "Armandyga Oktarivio", gender: "L", ortu: "Ony Purwanto (Alm)", univ: "", jurusan: "" },
      { no: 6, induk: "1952", nama: "Aulia Salma Azzahrah", gender: "P", ortu: "Mochammad Toyib", univ: "Universitas Negeri Malang", jurusan: "S1 Pendidikan Tata Boga" },
      { no: 7, induk: "1954", nama: "Aura Rizq Farsya Anandia", gender: "P", ortu: "Ir. Nanang Marsudi", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Desain Komunikasi Visual" },
      { no: 8, induk: "1976", nama: "Dava Irsyadul Ibad Maulidy", gender: "L", ortu: "Soejono", univ: "", jurusan: "" },
      { no: 9, induk: "1980", nama: "Deskta Syaputra", gender: "L", ortu: "Firman Wahyudi", univ: "", jurusan: "" },
      { no: 10, induk: "1982", nama: "Dewi Tri Andini", gender: "P", ortu: "Sukariadi", univ: "", jurusan: "" },
      { no: 11, induk: "2002", nama: "Ferdyan Arta Yudhistira", gender: "L", ortu: "Arianto", univ: "", jurusan: "" },
      { no: 12, induk: "2008", nama: "Gendhis Tri Arianti Sya'diah", gender: "P", ortu: "Agus Arianto", univ: "Universitas Negeri Surabaya", jurusan: "S1 Pendidikan IPS" },
      { no: 13, induk: "2015", nama: "Harist Al Mughny", gender: "L", ortu: "Mauidatul Hasanah", univ: "", jurusan: "" },
      { no: 14, induk: "2026", nama: "Jesica Aulia Rahma", gender: "P", ortu: "Chusnul", univ: "", jurusan: "" },
      { no: 15, induk: "2038", nama: "Khiar Gathan Abinaya", gender: "L", ortu: "Ahmad Junaidi", univ: "", jurusan: "" },
      { no: 16, induk: "2040", nama: "Kirana Maharani Wewengkang", gender: "P", ortu: "Tunggal Wahyu Wewengkang", univ: "Universitas Airlangga", jurusan: "S1 Antropologi" },
      { no: 17, induk: "2046", nama: "Muhammad Adam Fauzan", gender: "L", ortu: "Sumardiono", univ: "", jurusan: "" },
      { no: 18, induk: "2047", nama: "M. Dzaki Musyaffa", gender: "L", ortu: "M. Imron Wahyudi", univ: "", jurusan: "" },
      { no: 19, induk: "2064", nama: "Moh. Okta Surya Nugraha", gender: "L", ortu: "Muhamad Yusuf", univ: "", jurusan: "" },
      { no: 20, induk: "2088", nama: "Muhammad Rendra Putra Wardhana", gender: "L", ortu: "Rido Wasongko", univ: "", jurusan: "" },
      { no: 21, induk: "2097", nama: "Nabilla Jasmine Verlyana", gender: "P", ortu: "Candra Wijaya, S.T.", univ: "", jurusan: "" },
      { no: 22, induk: "2099", nama: "Nadia Aurellya Hariyanto", gender: "P", ortu: "Budi Hariyanto", univ: "", jurusan: "" },
      { no: 23, induk: "2105", nama: "Nathania Amellia Putri", gender: "P", ortu: "Suhar", univ: "", jurusan: "" },
      { no: 24, induk: "2113", nama: "Nisrina Fitri Andriani", gender: "P", ortu: "Andri Arifin", univ: "", jurusan: "" },
      { no: 25, induk: "2115", nama: "Nura Imanda Putri Zahra", gender: "P", ortu: "Nur Muchammad Fatachillah", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Ilmu Komunikasi" },
      { no: 26, induk: "2121", nama: "Rachel Septiya Noveliyanti", gender: "P", ortu: "Rais", univ: "", jurusan: "" },
      { no: 27, induk: "2123", nama: "Raditya Fairuz Zein", gender: "L", ortu: "Drs. Syawal, M.M.", univ: "", jurusan: "" },
      { no: 28, induk: "2190", nama: "Rahmania Candrawati Putri Sani", gender: "P", ortu: "Yoga Hizrahtul Sani", univ: "UPN Veteran Jawa Timur", jurusan: "S1 Agribisnis" },
      { no: 29, induk: "2132", nama: "Raka Putra Barutama", gender: "L", ortu: "Heka Yuliardi", univ: "", jurusan: "" },
      { no: 30, induk: "2161", nama: "Serafim Madjid", gender: "L", ortu: "Irfan Atria Musry Utama S.Psi", univ: "", jurusan: "" },
      { no: 31, induk: "2162", nama: "Sevy Areza Putri", gender: "P", ortu: "Atip Supriyono", univ: "Poltekkes Kemenkes Surabaya", jurusan: "D3 Kesehatan Gigi" },
      { no: 32, induk: "2166", nama: "Sultan Alif Farrely Prasetya", gender: "L", ortu: "Beny Eko Prasetyo", univ: "", jurusan: "" },
      { no: 33, induk: "2168", nama: "Tiara Ayudia Asfa", gender: "P", ortu: "Muhamad Fauzi Abdulah", univ: "", jurusan: "" },
      { no: 34, induk: "2172", nama: "Tsabitah Naura Putri", gender: "P", ortu: "Moch. Sya'roni", univ: "Universitas Airlangga (Kesehatan Masyarakat) & Poltekkes Kemenkes Surabaya (Sanitasi)", jurusan: "S1 Kesehatan Masyarakat / D3 Sanitasi" },
      { no: 35, induk: "2180", nama: "Wildan Mustafit Sabillillah", gender: "L", ortu: "Moh. Idam Hori", univ: "", jurusan: "" },
      { no: 36, induk: "2187", nama: "Zafira Khairun Nisa Anwar", gender: "P", ortu: "Khoirul Anwar", univ: "UIN Sunan Ampel Surabaya", jurusan: "S1 Psikologi" }
    ]
  }
};